### ISSUE TITLE
Can't convert undefined to object

### ISSUE THREAD

**Issue by SChetwynd** [hzmming/vue-force-dev#1]
If I try to use
`Object.defineProperty(()=>{}, "config", {})`
I get an error, because it tries to convert undefined to object on line 39.

This could be fixed by adding in a test for if `prototype === undefined`.

https://github.com/hzmming/vue-force-dev/blob/c9b9f44cb76ef6911ee137e4e033e789c94df89c/hack.js#L39

**Comment by hzmming** [comment]
Thanks for your issue，i've fixed it and submitted the release application, which is under review.

**Comment by hzmming** [comment]
The latest version has been released.
