### ISSUE TITLE
nuxtDetected incorrectly being true causes vue 2 to not get "cracked"

### ISSUE THREAD

**Issue by BryceBarbara** [hzmming/vue-force-dev#11]
I'm running into issues when debugging an internal UAT build of a tool at work and it appears to be caused by some missing fallback logic when `nuxtDetected` is true.

![image](https://github.com/hzmming/vue-force-dev/assets/24460210/6cc90838-b5b9-4aa2-b0dc-8875e8e004ce)

If I set a breakpoint on the line highlighted in the screenshot and then step through until I get to this line:
https://github.com/hzmming/vue-force-dev/blob/b2ce0dfe0ac84260e60b8d4d5c5625a15c9145d9/detector.js#L52

If I then change the value of `data.nuxtDetected` to `false` then the thing works correctly. I haven't looked too closely to see why, but I assume it's lacking some fallback logic inside the if statement.

**Comment by hzmming** [comment]
It seems that you have already solved the problem. (https://github.com/hzmming/vue-force-dev/pull/12)
