### ISSUE TITLE
Extension not working anymore in production mode

### ISSUE THREAD

**Issue by yannick-mir** [hzmming/vue-force-dev#16]
I was able to use the extension on my staging instances using Chrome before, now it suddenly stopped working. Firefox is still working as of now.

**Comment by lkounadis** [comment]
I confirm I have the same issue and firefox still works.

**Comment by MrEraxd** [comment]
It is because of new vue devtools version. It stoped working from v6.6.0. For now you can downgrade devtools. There is pending MR for this issue: https://github.com/hzmming/vue-force-dev/pull/15

**Comment by satoru-naito-axis** [comment]
Downgrades can be made [here](https://chromewebstore.google.com/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp).

**Comment by hzmming** [comment]
I have already released the latest version to solve the problem, thank you for your issue.
