### ISSUE TITLE
dose not work with the new devtools version 7.6.2

### ISSUE THREAD

**Issue by MordiSacks** [hzmming/vue-force-dev#18]
new vue devtools (7.6.2) seems to break

**Comment by prd-dat-tran** [comment]
I am also facing the issue for vue devtools (7.6.3).

**Comment by prd-dat-tran** [comment]
You're might using Vue 2. Seems that Vue Devtools 7 no longer supports it. Ref: https://github.com/vuejs/devtools/issues/652
Let's try [Vue.js Devtools Legacy](https://chromewebstore.google.com/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp)

**Comment by dmitryuk** [comment]
I use vue3 and vue-force-dev also not working

**Comment by hzmming** [comment]
Thanks for your issue，i've fixed it and submitted the release application, which is under review.

**Comment by hzmming** [comment]
The latest version has been released.

**Comment by MordiSacks** [comment]
Thank you!
