### ISSUE TITLE
Firefox addon

### ISSUE THREAD

**Issue by SChetwynd** [hzmming/vue-force-dev#2]
I've just tried loading the plug-in into Firefox, and it seems to works without issue and without any code changes.

Do you intend to release it for Firefox? If not, would you be OK with me publishing a fork of the project to Firefox addons?

**Comment by hzmming** [comment]
Thank you for your recognition of this extension. I will release it to Firebox and Microsoft edge in the near future.

**Comment by hzmming** [comment]
I've released it to Firefox.

https://addons.mozilla.org/en-US/firefox/addon/vue-force-dev/
