### ISSUE TITLE
vue-force-dev TypeError - 'version' undefined in Nuxt app

### ISSUE THREAD

**Issue by ddett** [hzmming/vue-force-dev#7]
I'm using the latest version of Vue-force-dev that was released on October 2, 2022 to force Vue in a Nuxt App.
nuxt@2.15.8 
vue@2.6.14

Vue is detected by the extension but the Vue panel does not appear. Instead I see this in the console:
```
vue-force-dev TypeError: Cannot read properties of undefined (reading 'version')
    at crackVue3 (<anonymous>:78:27)
    at crack (<anonymous>:42:11)
    at messageHander (<anonymous>:14:11)
```

Of course any help would be appreciated, thx!

**Comment by hzmming** [comment]
Thanks for your issue, the latest version has been released and fixed it.
